/** Auto-generated by scripts/fetch-uni-logos-node.mjs — do not edit by hand. */

export type UniOption = { value: string; label: string; logo: string };

export const SYSTEM_UNI_LOGOS = {
  azad: "/images/university/azad.jpg",
  payame_noor: "/images/university/payame_noor.jpg",
  applied_science: "/images/university/applied_science.svg",
} as const;

export const PUBLIC_UNIVERSITIES: UniOption[] = [
  {
    value: "iasbs",
    label: "پژوهشگاه تحصیلات تکمیلی علوم پایه زنجان",
    logo: "/images/university/iasbs.jpg"
  },
  {
    value: "arak",
    label: "دانشگاه اراک",
    logo: "/images/university/arak.svg"
  },
  {
    value: "urmia",
    label: "دانشگاه ارومیه",
    logo: "/images/university/urmia.svg"
  },
  {
    value: "isfahan",
    label: "دانشگاه اصفهان",
    logo: "/images/university/isfahan.png"
  },
  {
    value: "alzahra",
    label: "دانشگاه الزهرا",
    logo: "/images/university/alzahra.svg"
  },
  {
    value: "ilam",
    label: "دانشگاه ایلام",
    logo: "/images/university/ilam.jpg"
  },
  {
    value: "bojnord",
    label: "دانشگاه بجنورد",
    logo: "/images/university/bojnord.jpg"
  },
  {
    value: "bu_ali_sina",
    label: "دانشگاه بوعلی سینا",
    logo: "/images/university/bu_ali_sina.svg"
  },
  {
    value: "birjand",
    label: "دانشگاه بیرجند",
    logo: "/images/university/birjand.svg"
  },
  {
    value: "qazvin",
    label: "دانشگاه بین‌المللی امام خمینی",
    logo: "/images/university/qazvin.png"
  },
  {
    value: "tabriz",
    label: "دانشگاه تبریز",
    logo: "/images/university/tabriz.svg"
  },
  {
    value: "tarbiat_modares",
    label: "دانشگاه تربیت مدرس",
    logo: "/images/university/tarbiat_modares.png"
  },
  {
    value: "tehran",
    label: "دانشگاه تهران",
    logo: "/images/university/tehran.svg"
  },
  {
    value: "jahrom",
    label: "دانشگاه جهرم",
    logo: "/images/university/jahrom.jpg"
  },
  {
    value: "hakim_sabzevari",
    label: "دانشگاه حکیم سبزواری",
    logo: "/images/university/hakim_sabzevari.png"
  },
  {
    value: "persian_gulf",
    label: "دانشگاه خلیج فارس",
    logo: "/images/university/persian_gulf.png"
  },
  {
    value: "bushehr",
    label: "دانشگاه خلیج فارس بوشهر",
    logo: "/images/university/bushehr.png"
  },
  {
    value: "khaje_nasir",
    label: "دانشگاه خواجه نصیرالدین طوسی",
    logo: "/images/university/khaje_nasir.png"
  },
  {
    value: "kharazmi",
    label: "دانشگاه خوارزمی",
    logo: "/images/university/kharazmi.jpg"
  },
  {
    value: "damghan",
    label: "دانشگاه دامغان",
    logo: "/images/university/damghan.svg"
  },
  {
    value: "razi",
    label: "دانشگاه رازی",
    logo: "/images/university/razi.png"
  },
  {
    value: "zabol",
    label: "دانشگاه زابل",
    logo: "/images/university/zabol.jpg"
  },
  {
    value: "zanjan",
    label: "دانشگاه زنجان",
    logo: "/images/university/zanjan.svg"
  },
  {
    value: "kazerun_salman",
    label: "دانشگاه سلمان فارسی کازرون",
    logo: "/images/university/kazerun_salman.jpg"
  },
  {
    value: "semnan",
    label: "دانشگاه سمنان",
    logo: "/images/university/semnan.png"
  },
  {
    value: "sistan",
    label: "دانشگاه سیستان و بلوچستان",
    logo: "/images/university/sistan.jpg"
  },
  {
    value: "shahrekord",
    label: "دانشگاه شهرکرد",
    logo: "/images/university/shahrekord.svg"
  },
  {
    value: "shahid_bahonar",
    label: "دانشگاه شهید باهنر کرمان",
    logo: "/images/university/shahid_bahonar.png"
  },
  {
    value: "shahid_beheshti",
    label: "دانشگاه شهید بهشتی",
    logo: "/images/university/shahid_beheshti.jpg"
  },
  {
    value: "shahid_chamran",
    label: "دانشگاه شهید چمران اهواز",
    logo: "/images/university/shahid_chamran.png"
  },
  {
    value: "madani_azar",
    label: "دانشگاه شهید مدنی آذربایجان",
    logo: "/images/university/madani_azar.png"
  },
  {
    value: "shiraz",
    label: "دانشگاه شیراز",
    logo: "/images/university/shiraz.jpg"
  },
  {
    value: "iribu",
    label: "دانشگاه صدا و سیما",
    logo: "/images/university/iribu.jpg"
  },
  {
    value: "industry_petroleum",
    label: "دانشگاه صنعت نفت",
    logo: "/images/university/industry_petroleum.jpg"
  },
  {
    value: "isfahan_tech",
    label: "دانشگاه صنعتی اصفهان",
    logo: "/images/university/isfahan_tech.svg"
  },
  {
    value: "amirkabir",
    label: "دانشگاه صنعتی امیرکبیر",
    logo: "/images/university/amirkabir.png"
  },
  {
    value: "sahand",
    label: "دانشگاه صنعتی سهند",
    logo: "/images/university/sahand.png"
  },
  {
    value: "shahrood_tech",
    label: "دانشگاه صنعتی شاهرود",
    logo: "/images/university/shahrood_tech.svg"
  },
  {
    value: "sharif",
    label: "دانشگاه صنعتی شریف",
    logo: "/images/university/sharif.png"
  },
  {
    value: "malek_ashtar",
    label: "دانشگاه صنعتی مالک اشتر",
    logo: "/images/university/malek_ashtar.png"
  },
  {
    value: "babol_noshirvani",
    label: "دانشگاه صنعتی نوشیروانی بابل",
    logo: "/images/university/babol_noshirvani.png"
  },
  {
    value: "allameh",
    label: "دانشگاه علامه طباطبائی",
    logo: "/images/university/allameh.png"
  },
  {
    value: "iust",
    label: "دانشگاه علم و صنعت ایران",
    logo: "/images/university/iust.jpg"
  },
  {
    value: "ferdowsi",
    label: "دانشگاه فردوسی مشهد",
    logo: "/images/university/ferdowsi.svg"
  },
  {
    value: "farhangian",
    label: "دانشگاه فرهنگیان",
    logo: "/images/university/farhangian.svg"
  },
  {
    value: "qom",
    label: "دانشگاه قم",
    logo: "/images/university/qom.png"
  },
  {
    value: "kashan",
    label: "دانشگاه کاشان",
    logo: "/images/university/kashan.jpg"
  },
  {
    value: "kurdistan",
    label: "دانشگاه کردستان",
    logo: "/images/university/kurdistan.png"
  },
  {
    value: "golestan",
    label: "دانشگاه گلستان",
    logo: "/images/university/golestan.png"
  },
  {
    value: "gonbad",
    label: "دانشگاه گنبد کاووس",
    logo: "/images/university/gonbad.png"
  },
  {
    value: "guilan",
    label: "دانشگاه گیلان",
    logo: "/images/university/guilan.png"
  },
  {
    value: "lorestan",
    label: "دانشگاه لرستان",
    logo: "/images/university/lorestan.png"
  },
  {
    value: "mazandaran",
    label: "دانشگاه مازندران",
    logo: "/images/university/mazandaran.jpg"
  },
  {
    value: "maragheh",
    label: "دانشگاه مراغه",
    logo: "/images/university/maragheh.svg"
  },
  {
    value: "malayer",
    label: "دانشگاه ملایر",
    logo: "/images/university/malayer.jpg"
  },
  {
    value: "valiasr_rafsanjan",
    label: "دانشگاه ولی‌عصر رفسنجان",
    logo: "/images/university/valiasr_rafsanjan.svg"
  },
  {
    value: "hormozgan",
    label: "دانشگاه هرمزگان",
    logo: "/images/university/hormozgan.svg"
  },
  {
    value: "art_uni",
    label: "دانشگاه هنر",
    logo: "/images/university/art_uni.svg"
  },
  {
    value: "yasouj",
    label: "دانشگاه یاسوج",
    logo: "/images/university/yasouj.svg"
  },
  {
    value: "yazd",
    label: "دانشگاه یزد",
    logo: "/images/university/yazd.jpg"
  },
];

export const PUBLIC_UNIVERSITY_OTHER = "other";


/** Resolve logo path for an education row (system unit / public uni / none). */
export function educationLogoUrl(
  institutionType?: string | null,
  schoolName?: string | null,
): string | undefined {
  if (institutionType === "azad" || institutionType === "payame_noor" || institutionType === "applied_science") {
    return SYSTEM_UNI_LOGOS[institutionType];
  }
  if (institutionType === "public" && schoolName) {
    const match = PUBLIC_UNIVERSITIES.find((u) => u.label === schoolName);
    return match?.logo;
  }
  return undefined;
}
